### ISSUE TITLE
External clock counter returns 0 for 80 MHZ test.

### ISSUE THREAD

**Issue by rbelanger-thorlabs** [thorlabs-tsi/ThorDAQ_Issues#8]

**Comment by jmills-thorlabs** [comment]
This needs to be tested to make sure it is still not working. This may have been resolved with another fix.

**Comment by jmills-thorlabs** [comment]
Leo will retest today. He was still seeing this in January.

**Comment by rbelanger-thorlabs** [comment]
Correct Operation + ThorImage configuration was provided by Zhun
Correct Operation through FPGA register reads with arbitrary Laser Clock input was provided by myself.

Common thought is there may be an issue with Leo's hardware and/or configuration. More testing will be done by Leo on his setup.

![thordaq_fpga_registerread_arb_clk](https://user-images.githubusercontent.com/35271236/38440617-fbeada7a-39af-11e8-953f-c9b87cd0e334.jpg)
![va_thorimage gui_capture](https://user-images.githubusercontent.com/35271236/38440618-fbfed1b0-39af-11e8-8a71-865a3aa9a0f6.jpg)

**Comment by LMandujano-thorlabs** [comment]
This feature seems to be working correctly now. Zhun and Ryan retested on their respective boards and did not see the issue. Closing the issue.
